Better file Creation/Renaming - WIP
vizhub-core/vzcode pull request #302
Opened 2023-11-01 23:03 UTC by DomaDude123

2023-11-01 23:35 UTC, curran requested changes
It looks like there's some old stuff in this PR that reverts things to an older version.

It might make sense to start fresh, branching from `main`, then add the new modal to the clean slate.

Will do local testing later to help identify the bug.

Thanks for this!

2023-11-01 23:35 UTC, curran commented on src/client/App.tsx
> +      setTimeout(() => {
It looks like you started from an older version of the code, and this PR is bringing back these old bits.

2023-11-02 01:48 UTC, curran commented on src/client/VZSidebar/index.tsx
> +      <CreateFileModal
Please run `npm run prettier` to address formatting issues. Thanks!

2023-11-02 01:48 UTC, curran commented on src/client/useFileCRUD.ts
> +    console.log("Here's filename in createFile- ", fileName)
```suggestion
```

2023-11-02 01:48 UTC, curran commented on src/client/useFileCRUD.ts
> +  const handleDeleteClick = useCallback(
Yeah this is old, it was replaced by new stuff in a refactoring.

2023-11-03 20:19 UTC, DomaDude123 commented
> It looks like there's some old stuff in this PR that reverts things to an older version.
> 
> It might make sense to start fresh, branching from `main`, then add the new modal to the clean slate.
> 
> Will do local testing later to help identify the bug.
> 
> Thanks for this!

I'm going to create a new branch and implement the Modal there. Will try to find that bug along the way and create a new PR when ready. Thanks!

2023-11-04 00:13 UTC, closed without merging