first check for desktop app electron
vizhub-core/vzcode pull request #668
Opened 2024-04-24 17:10 UTC by MandingoBrandon

https://github.com/vizhub-core/vzcode/pull/new/DesktopApp

2024-04-24 17:23 UTC, curran requested changes
This is amazing! Thank you so much for working on this.

I have a few points of feedback:

 * When I run `npm run dev`, I see the following error:
![image](https://github.com/vizhub-core/vzcode/assets/68416/cd2fd25c-2661-4c25-a2c5-927fd8408987)
 * I would prefer not to change the existing scripts in `package.json`, but rather introduce a new one for Electron
 * Let's keep `"main": "src/index.ts",` for now, since I believe that impacts how we can import from the package. I'm not sure what the benefit of changing this is.
 * The usage of `cors` seems like it may not be strictly necessary. Perhaps it is, but something worth looking into, if we can remove it as a dependency.

2024-04-26 14:27 UTC, curran commented
To summarize the additional changes I'd like to see before merging this:

 * Please revert `npm run dev` to the same as it was before, so that I and others can continue to develop VZCode without invoking Electron
 * Please add a separate script that starts up the electron app and server, and ideally document in the README the exact commands recommended to start the electron app
 * Please revert the `"main": "src/index.ts"`
 * Please check if it can still work without the `cors` dependency

Thank you so much!

2024-05-13 06:44 UTC, icoco commented
[maybe pkg also is another option ](https://github.com/icoco/vzcode/tree/anvil) 
still not done

2024-07-04 17:10 UTC, curran commented
Whoah thank you @icoco !

I'd still like to make this happen. Not sure what the easiest path is, but it would be great to be able to do this:

```
npm install -g vzcode
cd my-local-source-code-dir
vzcode .
```

then have the app open as an Electron app to edit my files locally.

2025-04-03 21:26 UTC, closed without merging