Rainbow bracket toggle button
vizhub-core/vzcode pull request #869
Opened 2024-10-11 20:39 UTC by TroyG-11

https://github.com/vizhub-core/vzcode/issues/722

Working on this right now, created a button so far to toggle.

2024-10-11 20:55 UTC, TroyG-11 commented
No current functionality as of yet, just added the button dropdowns.

2024-11-07 13:49 UTC, curran approved these changes
This looks like the right way to do it! Thank you so much for this.

2024-11-07 13:49 UTC, curran commented on src/client/CodeEditor/getOrCreateEditor.ts
> +// Extend the EditorCacheValue type to include the compartments and the updateRainbowBrackets method
Looks great!

2024-11-07 13:52 UTC, curran requested changes
I tested it and it seems like it does not work. Here's the screen recording of the test:


https://github.com/user-attachments/assets/c6b1a67c-a26d-4c1a-b448-c116016a3386

2024-11-07 15:49 UTC, TroyG-11 commented
> I tested it and it seems like it does not work. Here's the screen recording of the test:
> 
>  rainbowBracketsTest.mp4

Hi, I've been working on this on a separate branch right now. I had the PR up as a draft since it isn't completed yet. Will be finishing it up soon.

2024-11-26 21:09 UTC, TroyG-11 commented
Should be ready. 

It might have a quick delay before the render update on the rainbow brackets happen after switching toggle.

2024-11-27 13:46 UTC, curran approved these changes
LGTM! Tested locally and it works. There is a delay, it seems like maybe you need to interact with the editor for the change to take hold, but that's OK.

Thank you!

2024-11-27 13:46 UTC, merged